baseurl = "https://rahilw.dev/"
languagecode = "en-us"
defaultcontentlanguage = "en"
title = "Raheel Wazir"
theme = "hugo-coder"
enableRobotsTxt = true
enableGitInfo = true
enableEmoji = true

[params]
    hideCredits = true
    author = "Raheel Wazir"

[taxonomies]
  series = "series"

[[params.social]]
    name = "Github"
    icon = "fa fa-2x fa-github"
    url = "https://github.com/rahilwazir"

[[params.social]]
    name = "Stackoverflow"
    icon = "fa fa-2x fa-stack-overflow"
    url = "https://stackoverflow.com/users/2264626/rahil-wazir?tab=profile"

[[params.social]]
    name = "Twitter"
    icon = "fa fa-2x fa-twitter"
    url = "https://twitter.com/rahilwazir"

[[params.social]]
    name = "Linkedin"
    icon = "fa fa-2x fa-linkedin"
    url = "https://www.linkedin.com/in/rahil-wazir-ab417651"

[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 1
        url = "/blog/"

    [languages.ur-pk]
        languagename = "Urdu"
        title = "اردو"
        rtl = true