baseURL = "https://rahilw.dev/"
languageCode = "en-us"
title = "Rahil Wazir"
theme = "hello-friend-ng"
enableRobotsTxt = true
enableGitInfo = true

[params.Logo]
logoText = "rw"

[[params.Social]]
    name = "github"
    url = "https://github.com/rahilwazir"
[[params.Social]]
    name = "twitter"
    url = "https://twitter.com/rahilwazir"
[[params.Social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/rahil-wazir-ab417651"